### ISSUE TITLE
Unhandled exception:  (DB::ConnectionRefused)

### ISSUE THREAD

**Issue by X-tymchenko** [amberframework/amber#1167]
I just run `amber watch` and got this error: 
### Error message: 
```
Unhandled exception:  (DB::ConnectionRefused)
  from lib/pg/src/pg/connection.cr:16:9 in 'initialize'
  from lib/pg/src/pg/connection.cr:7:5 in 'new'
  from lib/pg/src/pg/driver.cr:3:5 in 'build_connection'
  from lib/db/src/db/database.cr:57:9 in '->'
  from lib/db/src/db/pool.cr:255:3 in 'build_resource'
  from lib/db/src/db/pool.cr:45:34 in 'initialize'
  from lib/db/src/db/pool.cr:38:5 in 'new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay'
  from lib/db/src/db/database.cr:56:15 in 'initialize'
  from lib/db/src/db/database.cr:49:5 in 'new'
  from lib/db/src/db.cr:152:5 in 'build_database'
  from lib/db/src/db.cr:148:5 in 'build_database'
  from lib/micrate/src/micrate/cli.cr:121:5 in 'run_up'
  from spec/spec_helper.cr:14:1 in '__crystal_main'
  from /home/linuxbrew/.linuxbrew/Cellar/crystal/0.31.1/src/crystal/main.cr:97:5 in 'main_user_code'
  from /home/linuxbrew/.linuxbrew/Cellar/crystal/0.31.1/src/crystal/main.cr:86:7 in 'main'
  from /home/linuxbrew/.linuxbrew/Cellar/crystal/0.31.1/src/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???
Caused by: password authentication failed for user "postgres" (PQ::PQError)
  from lib/pg/src/pq/connection.cr:203:7 in 'handle_error'
  from lib/pg/src/pq/connection.cr:186:7 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:157:7 in 'read'
  from lib/pg/src/pq/connection.cr:386:31 in 'expect_frame'
  from lib/pg/src/pq/connection.cr:385:5 in 'expect_frame'
  from lib/pg/src/pq/connection.cr:354:7 in 'handle_auth_md5'
  from lib/pg/src/pq/connection.cr:266:9 in 'handle_auth'
  from lib/pg/src/pq/connection.cr:95:9 in 'connect'
  from lib/pg/src/pg/connection.cr:14:9 in 'initialize'
  from lib/pg/src/pg/connection.cr:7:5 in 'new'
  from lib/pg/src/pg/driver.cr:3:5 in 'build_connection'
  from lib/db/src/db/database.cr:57:9 in '->'
  from lib/db/src/db/pool.cr:255:3 in 'build_resource'
  from lib/db/src/db/pool.cr:45:34 in 'initialize'
  from lib/db/src/db/pool.cr:38:5 in 'new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay'
  from lib/db/src/db/database.cr:56:15 in 'initialize'
  from lib/db/src/db/database.cr:49:5 in 'new'
  from lib/db/src/db.cr:152:5 in 'build_database'
  from lib/db/src/db.cr:148:5 in 'build_database'
  from lib/micrate/src/micrate/cli.cr:121:5 in 'run_up'
  from spec/spec_helper.cr:14:1 in '__crystal_main'
  from /home/linuxbrew/.linuxbrew/Cellar/crystal/0.31.1/src/crystal/main.cr:97:5 in 'main_user_code'
  from /home/linuxbrew/.linuxbrew/Cellar/crystal/0.31.1/src/crystal/main.cr:86:7 in 'main'
  from /home/linuxbrew/.linuxbrew/Cellar/crystal/0.31.1/src/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```
But after i have access to DB. And I can select + insert data
### Dependencies:
```
dependencies:
  amber:
    github: amberframework/amber
    version: 0.31.0
    branch: master

  granite:
    github: amberframework/granite
    version: ~> 0.17.3

  quartz_mailer:
    github: amberframework/quartz-mailer
    version: ~> 0.5.3

  jasper_helpers:
    github: amberframework/jasper-helpers
    version: ~> 0.2.4

  pg:
    github: will/crystal-pg
    version: ~> 0.19.0

  citrine-i18n:
    github: amberframework/citrine-i18n
    version: 0.4.0
```
