### ISSUE TITLE
Unable to create a test database when DATABASE_URL is present

### ISSUE THREAD

**Issue by John-Hayes-Reed** [amberframework/amber#1190]
### Description

When trying to create a `_test` database using a docker-compose service based project that is supplying a DATABASE_URL environment variable to the service, it does not create a test database, and shows an `xxxxxxx_development database already exists` message.

### Steps to Reproduce

1. Create a new Amber project
2. Ensure the generate docker-compose.yml file is supplying an `_development` DATABASE_URL to the main `app` service, like:
```yaml
services:
  app:
  build: .
  image: example_app
  command: amber watch
  environment:
    DATABASE_URL: postgres://admin:password@db:5432/scrumple_development
  ports:
    - 3000:3000
  links:
    - db
  volumes:
  - .:/app
  - nodes:/app/node_modules
  - shards:/app/lib
```
3. Enter into the container with the bash command: `docker-compose run app bash`
4. Run CLI command to create test database: `AMBER_ENV=test amber db create`

**Expected behavior:** [What you expect to happen]

A `xxxxxxxx_test` database to be created.

**Actual behavior:** [What actually happens]

A message appears with: `xxxxxxxx_development database already exists` and no test database is created.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time so far for my one project, have not tried this after generating a second project though.

### Versions

- Amber CLI (amberframework.org) - v0.32.0
- Crystal 0.33.0 [612825a53] (2020-02-14)
- Image: amberframework/amber:0.33.0

On MacOS 10.14.6, Running Docker Desktop 2.2.0.4 with Docker Engine 19.03.8 and Compose 1.25.4
