### ISSUE TITLE
Techempower Benchmark 19 did not complete

### ISSUE THREAD

**Issue by eliasjpr** [amberframework/amber#1226]
### Description

The benchmark did not complete see  https://www.techempower.com/benchmarks/ at the bottom of the list. 

It would be great to get this running again for the next round.

**Comment by andrewc910** [comment]
```yml
name: amber
version: 0.1.0

authors:
  - Amber Team and Contributors <amberframework.org>

license: MIT

targets:
  amber:
    main: src/amber.cr

dependencies:
  amber:
    github: amberframework/amber
    version: 0.9.0

  granite:
    github: amberframework/granite
    version: 0.13.1
```

Here is the shard file for the amber project they have in the repo. `Amber 0.9.0`...

Just generate a new project & open a PR? I can get that done if that's how to do it.
