### ISSUE TITLE
Automatically generated mock data files

### ISSUE THREAD

**Issue by HCLarsen** [amberframework/amber#1345]
This would operate similar to Rails' `fixture` folder, with the generator creating a file for each model generated, and those models being automatically included in the test files, to be easily used in tests.

In Rails, this file takes the form of yaml, with two mock objects, like so:

```
david:
  name: David Heinemeier Hansson
  birthday: 1979-10-15
  profession: Systems development

steve:
  name: Steve Ross Kellock
  birthday: 1974-09-27
  profession: guy with keyboard
```

And they're included with a method with the same name as the model.

```
users(:david)
```

We don't necessarily have to use the same syntax as Rails, but something just as easy to use, or easier, would be a great benefit to those of us who wish to use TDD with our Amber apps.
