### ISSUE TITLE
Remove commented branch master line from generated projects

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#759]
### Description

Currently, the `shard.yml` file in projects generated by `amber new` has this:

```yaml
dependencies:
  amber:
    github: amberframework/amber
    version: 0.7.2
    #branch: master
``` 

~~Why we are using this line `#branch: master`, well, I guess is because tests, right?~~

~~Because we, need to have `branch: master` in our master branch to execute tests successfully:~~

https://github.com/amberframework/amber/blob/bea1063f640e0c7466989fd50cd0453b812d7a39/src/amber/cli/templates/app/shard.yml.ecr#L18-L22

~~So, then I think we can avoid that by using this code:~~ :no_good_man: 

```yaml
dependencies:
  amber:
    github: amberframework/amber
    <%- if ENV["AMBER_ENV"]? == "test" -%>
    branch: master
    <%- else -%>
    version: <%= Amber::VERSION %>
    <%- end -%>
``` 

~~We are already using `AMBER_ENV=test` in for the specs, so I think this would work well (tested locally)~~

### Steps to Reproduce

1. Generate new project
2. Open `shard.yml`

**Expected behavior:** See:

```yaml
dependencies:
  amber:
    github: amberframework/amber
    version: 0.7.2
``` 

**Actual behavior:** [What actually happens]

```yaml
dependencies:
  amber:
    github: amberframework/amber
    version: 0.7.2
    #branch: master
``` 

**Reproduces how often:** 100%

### Versions

0.7.2

### Additional Information

~~Already @robacarp tried to fix something similar in https://github.com/amberframework/amber/pull/727, although I think this would be a better approach. I will open a PR about this soon~~

~~BTW, I think if we do this then we don't need to use the @elorest script anymore to change (comment/uncomment) lines, before every release, so the steps before releasing will be easier:~~ :no_good_man: 

0. Testing, testing and more testing (no to believe just in Travis :stuck_out_tongue_winking_eye: )

1 Change versions on `shard.yml` and `version.cr`
2. Create the  proper tag
3. Publishing a new release.

WDYT?
