### ISSUE TITLE
[CLI] - Batch generation from yaml file

### ISSUE THREAD

**Issue by sumwatt** [amberframework/amber#773]
It would be nice to have a feature in the CLI whereby you can enter a command to parse a yaml file and generate multiple models, classes and views from the yaml file.

Example command:

```amber batch mysite.yml```

... that will process a file like:

```
Model:
  Post:
    - "title:string"
    - "body:text"
    - "user:reference"
  User:
    - "name:string"
    - "password:string"
  Comment:
    - "title:string"
    - "body:text"
    - "user:reference"
```

It will use the CLI generator to create all of the Models, Views, and Controllers in a single step.

An alternative syntax may be something like:

```
Post:
  Model:
      - "title:string"
      - "body:text"
      - "user:reference"
  Controller:
    {goes here}
  View:
    {goes here}
User:
  Model:
    - "name:string"
    - "password:string"
  Controller:
    {goes here}
  View:
    {goes here}
Comment:
  Model:
    - "title:string"
    - "body:text"
    - "user:reference"
  Controller:
    {goes here}
  View:
    {goes here}
```

### Use case
I was looking at the RealWorld project and started mocking up a model based on [API specs](https://github.com/gothinkster/realworld/tree/master/api) using Yaml as it allows me to visualize how the application needs to be modeled. Since YAML files generally have structure, it was visually helpful to see the application layout before generating.

But I thought it might also be useful for:

- If you're trying to translate customer/stakeholder requirements into a structured form, you write a template to feed to the Amber generator
- You are porting an application to Amber and you want to translate the basic underpinnings of the application to a project skeleton
