### ISSUE TITLE
Upgrade project from 0.8.0 to 0.9.0

### ISSUE THREAD

**Issue by proyb6** [amberframework/amber#953]
I can see a few devs' repo using Amber 0.8.0 and I have modified to work use recently tags and in my struggle, granite is hard to debug. Is it recommend to upgrade?

Using Crystal 0.26.1 on macOS Mojave.

```
dependencies:
  amber:
    github: amberframework/amber
    version: 0.9.0
    #branch: master

  granite:
    github: amberframework/granite
    version: ~> 0.14.0
```

https://github.com/TheNocturneProject/nocturne
```
in macro 'has_many' /Users/crystal/Downloads/nocturne-master/lib/granite/src/granite/associations.cr:52, line 8:

   1.
   2.
   3.
   4.
   5.
   6.
   7.     def village_buildings
>  8.       Granite::AssociationCollection(self, VillageBuildings).new(self, "village_id", nil)
   9.     end
  10.

undefined constant VillageBuildings (did you mean 'VillageBuilding')
```
